#!/usr/bin/env python3
"""
H5 Lens - Build Script
Generates a .spec file then builds with PyInstaller.

Usage:
    python build.py           # Single .exe
    python build.py --onedir  # Directory bundle (recommended)
"""

import subprocess
import sys
import os
import shutil
from pathlib import Path


def find_package_path(pkg_name):
    """Find the actual installed path of a package."""
    try:
        mod = __import__(pkg_name)
        p = Path(mod.__file__).parent
        return str(p)
    except Exception:
        return None


def main():
    base = Path(__file__).parent
    onedir = "--onedir" in sys.argv

    # Ensure PyInstaller
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("Installing PyInstaller...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])

    # Clean
    for d in ["build", "dist"]:
        p = base / d
        if p.exists():
            shutil.rmtree(p)
    for f in base.glob("*.spec"):
        f.unlink()

    # Find package paths to bundle as data
    pkg_paths = {}
    for pkg in ["h5py", "numpy", "PIL", "webview"]:
        p = find_package_path(pkg)
        if p:
            pkg_paths[pkg] = p
            print(f"  Found {pkg}: {p}")
        else:
            print(f"  WARNING: {pkg} not found")

    # Build datas list for .spec
    datas_lines = []
    datas_lines.append(f"    (r'{base / 'lib' / 'viewer.html'}', 'lib'),")
    datas_lines.append(f"    (r'{base / 'config.json'}', '.'),")

    # Bundle entire package directories as data
    for pkg, path in pkg_paths.items():
        # e.g. (r'C:\Python\Lib\site-packages\h5py', 'h5py')
        datas_lines.append(f"    (r'{path}', '{pkg}'),")

    # Also find and bundle hdf5.dll / hdf5_hl.dll etc.
    # These are often in h5py/.libs or h5py.libs
    if "h5py" in pkg_paths:
        h5py_parent = Path(pkg_paths["h5py"]).parent
        # Check for h5py.libs (pip-installed wheels put DLLs here)
        h5py_libs = h5py_parent / "h5py.libs"
        if h5py_libs.exists():
            datas_lines.append(f"    (r'{h5py_libs}', 'h5py.libs'),")
            print(f"  Found h5py.libs: {h5py_libs}")
        # Check for .libs inside h5py
        h5py_dot_libs = Path(pkg_paths["h5py"]) / ".libs"
        if h5py_dot_libs.exists():
            datas_lines.append(f"    (r'{h5py_dot_libs}', 'h5py/.libs'),")
            print(f"  Found h5py/.libs: {h5py_dot_libs}")

    # numpy.libs too
    if "numpy" in pkg_paths:
        np_parent = Path(pkg_paths["numpy"]).parent
        np_libs = np_parent / "numpy.libs"
        if np_libs.exists():
            datas_lines.append(f"    (r'{np_libs}', 'numpy.libs'),")
            print(f"  Found numpy.libs: {np_libs}")

    datas_str = "\n".join(datas_lines)

    # Hidden imports
    hiddenimports = [
        "lib", "lib.app", "lib.h5engine",
        "h5py", "h5py._hl", "h5py._hl.files", "h5py._hl.group", "h5py._hl.dataset",
        "h5py.defs", "h5py.utils", "h5py._errors", "h5py._objects", "h5py._conv",
        "numpy", "numpy.core", "numpy.core._methods", "numpy.core._dtype_ctypes",
        "numpy.random", "numpy.linalg", "numpy.fft",
        "PIL", "PIL.Image", "PIL.PngImagePlugin",
        "webview",
        "webview.platforms.winforms",
        "webview.platforms.cocoa",
        "webview.platforms.gtk",
        "webview.platforms.qt",
        "clr", "System.Windows.Forms", "System.Threading",
    ]
    hidden_str = ",\n        ".join(f"'{h}'" for h in hiddenimports)

    mode_str = "False" if onedir else "True"  # True = onefile

    spec_content = f"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build.py

a = Analysis(
    [r'{base / "launch.py"}'],
    pathex=[r'{base}'],
    binaries=[],
    datas=[
{datas_str}
    ],
    hiddenimports=[
        {hidden_str}
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    {'a.binaries, a.datas,' if not onedir else ''}
    [],
    exclude_binaries={'True' if onedir else 'False'},
    name='H5Lens',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
)
"""

    if onedir:
        spec_content += f"""
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    name='H5Lens',
)
"""

    spec_path = base / "H5Lens.spec"
    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(spec_content)

    print()
    print("=" * 60)
    print("  H5 Lens - Building executable")
    print("=" * 60)
    print(f"  Mode: {'onedir' if onedir else 'onefile'}")
    print(f"  Spec: {spec_path}")
    print()

    cmd = [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", str(spec_path)]
    subprocess.check_call(cmd, cwd=str(base))

    print()
    print("=" * 60)
    print("  Build complete!")
    if onedir:
        print("  Output: dist/H5Lens/H5Lens.exe")
    else:
        exe_name = f"H5Lens{'.exe' if sys.platform == 'win32' else ''}"
        print(f"  Output: dist/{exe_name}")
    print("=" * 60)


if __name__ == "__main__":
    main()
